version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.5
      - image: circleci/postgres:10.4-ram
        environment:
          POSTGRES_USER: jo-eunbyeol
          POSTGRES_DB: jamie
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run: npm install
      - run:
          name: psql
          command: psql -U jo-eunbyeol -d jamie-f schema.sql -h localhost

      - run: npm test


