version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.5
      - image: circleci/postgres:10.4-alpine-postgis
        environment:
          POSTGRES_HOST: localhost
          POSTGRES_USER: jo-eunbyeol
          POSTGRES_DB: jamie
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run: npm install
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://jo-eunbyeol@localhost:5432/jamie"
      - run: npm test


