version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.5
      - image: circleci/golang:1.8-jessie
      - image: circleci/postgres:10.4-ram
        environment:
          POSTGRES_USER: jo-eunbyeol
          POSTGRES_DB: jamie
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-go

    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: npm install
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run unit tests
          environment:
            CONTACTS_DB_URL: "postgres://jo-eunbyeol@localhost:5432/jamie?sslmode=disable"
            CONTACTS_DB_MIGRATIONS: /go/src/github.com/CircleCI-Public/circleci-demo-go/db/migrations
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - run: make

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - run:
          name: Start service
          environment:
            CONTACTS_DB_URL: "postgres://jo-eunbyeol@localhost:5432/jamie?sslmode=disable"
            CONTACTS_DB_MIGRATIONS: /go/src/github.com/CircleCI-Public/circleci-demo-go/db/migrations
          command: ./workdir/contacts
          background: true
      - run:
        name: install postgresql-client
        command: |
          apk update
          apk add postgresql-client
      - run:
          name: psql
          command: time psql -q -h localhost -p 5432 -U jo-eunbyeol -d jamie -c '\timing' -f schema.sql > /dev/null
      - run: npm test


