version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.5
      - image: circleci/postgres:10.4-ram
        environment:
          POSTGRES_USER: jo-eunbyeol
          POSTGRES_DB: jamie
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run: npm install
      - run:
          name: setup
          command: sudo apt-get install -y postgresql
      - run:
          name: psql
          command: time psql -q -h localhost -p 5432 -U jo-eunbyeol -d jamie -c '\timing' -f schema.sql > /dev/null
      - run: npm test


